apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - configmap.yaml
  - api-deployment.yaml
  - worker-deployment.yaml
  - service.yaml
  - pdb.yaml
  - hpa.yaml
  - networkpolicy.yaml
commonLabels:
  app.kubernetes.io/name: konfid
