"""initial schema
Revision ID: 21d43ef07e30
Revises: 
Create Date: 2026-10-02 03:13:25.226609
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '21d43ef07e30'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_policies',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant', sa.String(length=128), nullable=False),
    sa.Column('operation', sa.String(length=128), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('eligible_roles', sa.JSON(), nullable=False),
    sa.Column('distinct_humans', sa.Boolean(), nullable=False),
    sa.Column('requester_may_approve', sa.Boolean(), nullable=False),
    sa.Column('operator_may_approve', sa.Boolean(), nullable=False),
    sa.Column('required_assurance', sa.String(length=64), nullable=False),
    sa.Column('max_auth_age_seconds', sa.Integer(), nullable=False),
    sa.Column('approval_ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('justification_required', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant', 'operation', name='uq_approval_operation')
    )
    op.create_index(op.f('ix_approval_policies_tenant'), 'approval_policies', ['tenant'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant', sa.String(length=128), nullable=False),
    sa.Column('requester_principal', sa.String(length=64), nullable=False),
    sa.Column('operation', sa.String(length=128), nullable=False),
    sa.Column('target', sa.String(length=256), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('request_digest', sa.String(length=128), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('policy_ref', sa.String(length=128), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_expires_at'), 'approval_requests', ['expires_at'], unique=False)
    op.create_index(op.f('ix_approval_requests_request_digest'), 'approval_requests', ['request_digest'], unique=False)
    op.create_index(op.f('ix_approval_requests_requester_principal'), 'approval_requests', ['requester_principal'], unique=False)
    op.create_index(op.f('ix_approval_requests_state'), 'approval_requests', ['state'], unique=False)
    op.create_index(op.f('ix_approval_requests_tenant'), 'approval_requests', ['tenant'], unique=False)
    op.create_table('audit_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant', sa.String(length=128), nullable=False),
    sa.Column('actor_principal', sa.String(length=64), nullable=True),
    sa.Column('caller_service', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=256), nullable=False),
    sa.Column('target_ref', sa.String(length=256), nullable=True),
    sa.Column('outcome', sa.String(length=64), nullable=False),
    sa.Column('correlation_id', sa.String(length=128), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('event_digest', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exported', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_records_action'), 'audit_records', ['action'], unique=False)
    op.create_index(op.f('ix_audit_records_correlation_id'), 'audit_records', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_records_exported'), 'audit_records', ['exported'], unique=False)
    op.create_index(op.f('ix_audit_records_tenant'), 'audit_records', ['tenant'], unique=False)
    op.create_table('delegations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant', sa.String(length=128), nullable=False),
    sa.Column('from_principal', sa.String(length=64), nullable=False),
    sa.Column('to_principal', sa.String(length=64), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('resource_classes', sa.JSON(), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_chain_depth', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('issued_by', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delegations_from_principal'), 'delegations', ['from_principal'], unique=False)
    op.create_index(op.f('ix_delegations_status'), 'delegations', ['status'], unique=False)
    op.create_index(op.f('ix_delegations_tenant'), 'delegations', ['tenant'], unique=False)
    op.create_index(op.f('ix_delegations_to_principal'), 'delegations', ['to_principal'], unique=False)
    op.create_table('detector_definitions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant', sa.String(length=128), nullable=False),
    sa.Column('detector_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('input_schema', sa.String(length=128), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('rollout', sa.JSON(), nullable=False),
    sa.Column('package_digest', sa.String(length=128), nullable=False),
    sa.Column('qualification_ref', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant', 'detector_id', 'version', name='uq_detector_version')
    )
    op.create_index(op.f('ix_detector_definitions_tenant'), 'detector_definitions', ['tenant'], unique=False)
    op.create_table('grants',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant', sa.String(length=128), nullable=False),
    sa.Column('subject_ref', sa.String(length=64), nullable=False),
    sa.Column('role_ref', sa.String(length=128), nullable=True),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('resource_classes', sa.JSON(), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issued_by', sa.String(length=128), nullable=False),
    sa.Column('policy_version', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grants_status'), 'grants', ['status'], unique=False)
    op.create_index(op.f('ix_grants_subject_ref'), 'grants', ['subject_ref'], unique=False)
    op.create_index(op.f('ix_grants_tenant'), 'grants', ['tenant'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant', sa.String(length=128), nullable=False),
    sa.Column('topic', sa.String(length=256), nullable=False),
    sa.Column('aggregate_ref', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant', 'topic', 'aggregate_ref', name='uq_outbox_topic_aggregate')
    )
    op.create_index(op.f('ix_outbox_events_aggregate_ref'), 'outbox_events', ['aggregate_ref'], unique=False)
    op.create_index(op.f('ix_outbox_events_next_attempt_at'), 'outbox_events', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_outbox_events_state'), 'outbox_events', ['state'], unique=False)
    op.create_index(op.f('ix_outbox_events_tenant'), 'outbox_events', ['tenant'], unique=False)
    op.create_index(op.f('ix_outbox_events_topic'), 'outbox_events', ['topic'], unique=False)
    op.create_table('principals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('risk_state', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_principals_status'), 'principals', ['status'], unique=False)
    op.create_index(op.f('ix_principals_tenant'), 'principals', ['tenant'], unique=False)
    op.create_table('resource_classes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant', sa.String(length=128), nullable=False),
    sa.Column('owner_system', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('classification', sa.String(length=64), nullable=False),
    sa.Column('supported_actions', sa.JSON(), nullable=False),
    sa.Column('attributes_schema', sa.JSON(), nullable=False),
    sa.Column('policy_namespace', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant', 'owner_system', 'name', name='uq_resource_class')
    )
    op.create_index(op.f('ix_resource_classes_tenant'), 'resource_classes', ['tenant'], unique=False)
    op.create_table('response_actions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant', sa.String(length=128), nullable=False),
    sa.Column('requester_principal', sa.String(length=64), nullable=False),
    sa.Column('risk_signal_ids', sa.JSON(), nullable=False),
    sa.Column('operation', sa.String(length=128), nullable=False),
    sa.Column('target', sa.String(length=256), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('requester_auth_assurance', sa.String(length=64), nullable=False),
    sa.Column('requester_auth_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('decision_ref', sa.String(length=128), nullable=True),
    sa.Column('approval_request_id', sa.String(length=64), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_receipt', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant', 'idempotency_key', name='uq_response_idem')
    )
    op.create_index(op.f('ix_response_actions_expires_at'), 'response_actions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_response_actions_operation'), 'response_actions', ['operation'], unique=False)
    op.create_index(op.f('ix_response_actions_requester_principal'), 'response_actions', ['requester_principal'], unique=False)
    op.create_index(op.f('ix_response_actions_state'), 'response_actions', ['state'], unique=False)
    op.create_index(op.f('ix_response_actions_tenant'), 'response_actions', ['tenant'], unique=False)
    op.create_table('risk_signals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant', sa.String(length=128), nullable=False),
    sa.Column('subject_ref', sa.String(length=64), nullable=True),
    sa.Column('target_ref', sa.String(length=256), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('detector_id', sa.String(length=128), nullable=False),
    sa.Column('detector_version', sa.String(length=64), nullable=False),
    sa.Column('reason_codes', sa.JSON(), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_signals_expires_at'), 'risk_signals', ['expires_at'], unique=False)
    op.create_index(op.f('ix_risk_signals_severity'), 'risk_signals', ['severity'], unique=False)
    op.create_index(op.f('ix_risk_signals_subject_ref'), 'risk_signals', ['subject_ref'], unique=False)
    op.create_index(op.f('ix_risk_signals_tenant'), 'risk_signals', ['tenant'], unique=False)
    op.create_table('role_mailboxes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant', sa.String(length=128), nullable=False),
    sa.Column('address', sa.String(length=320), nullable=False),
    sa.Column('role_ref', sa.String(length=128), nullable=False),
    sa.Column('confidentiality_class', sa.String(length=64), nullable=False),
    sa.Column('delivery_policy', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant', 'address', name='uq_role_mailbox')
    )
    op.create_index(op.f('ix_role_mailboxes_tenant'), 'role_mailboxes', ['tenant'], unique=False)
    op.create_table('security_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant', sa.String(length=128), nullable=False),
    sa.Column('subject_ref', sa.String(length=64), nullable=True),
    sa.Column('caller_service', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=256), nullable=True),
    sa.Column('resource_class', sa.String(length=256), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_subject_time', 'security_events', ['tenant', 'subject_ref', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_security_events_event_type'), 'security_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_events_occurred_at'), 'security_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_security_events_subject_ref'), 'security_events', ['subject_ref'], unique=False)
    op.create_index(op.f('ix_security_events_tenant'), 'security_events', ['tenant'], unique=False)
    op.create_table('account_bindings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant', sa.String(length=128), nullable=False),
    sa.Column('principal_id', sa.String(length=64), nullable=False),
    sa.Column('system', sa.String(length=128), nullable=False),
    sa.Column('external_account_id', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant', 'system', 'external_account_id', name='uq_account_binding')
    )
    op.create_index(op.f('ix_account_bindings_principal_id'), 'account_bindings', ['principal_id'], unique=False)
    op.create_index(op.f('ix_account_bindings_tenant'), 'account_bindings', ['tenant'], unique=False)
    op.create_table('approval_receipts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant', sa.String(length=128), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('approver_principal', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('request_digest', sa.String(length=128), nullable=False),
    sa.Column('auth_assurance', sa.String(length=64), nullable=False),
    sa.Column('auth_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('policy_ref', sa.String(length=128), nullable=False),
    sa.Column('orgo_case_ref', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['approval_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'approver_principal', name='uq_approval_approver')
    )
    op.create_index(op.f('ix_approval_receipts_approver_principal'), 'approval_receipts', ['approver_principal'], unique=False)
    op.create_index(op.f('ix_approval_receipts_request_id'), 'approval_receipts', ['request_id'], unique=False)
    op.create_index(op.f('ix_approval_receipts_tenant'), 'approval_receipts', ['tenant'], unique=False)
    op.create_table('contact_endpoints',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant', sa.String(length=128), nullable=False),
    sa.Column('principal_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('value_normalized', sa.String(length=512), nullable=False),
    sa.Column('verification_state', sa.String(length=32), nullable=False),
    sa.Column('purpose', sa.JSON(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_endpoints_principal_id'), 'contact_endpoints', ['principal_id'], unique=False)
    op.create_index(op.f('ix_contact_endpoints_tenant'), 'contact_endpoints', ['tenant'], unique=False)
    op.create_table('detection_feedback',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant', sa.String(length=128), nullable=False),
    sa.Column('risk_signal_id', sa.String(length=64), nullable=False),
    sa.Column('analyst_principal', sa.String(length=64), nullable=False),
    sa.Column('classification', sa.String(length=32), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['risk_signal_id'], ['risk_signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_feedback_analyst_principal'), 'detection_feedback', ['analyst_principal'], unique=False)
    op.create_index(op.f('ix_detection_feedback_classification'), 'detection_feedback', ['classification'], unique=False)
    op.create_index(op.f('ix_detection_feedback_risk_signal_id'), 'detection_feedback', ['risk_signal_id'], unique=False)
    op.create_index(op.f('ix_detection_feedback_tenant'), 'detection_feedback', ['tenant'], unique=False)
    op.create_table('identity_bindings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant', sa.String(length=128), nullable=False),
    sa.Column('principal_id', sa.String(length=64), nullable=False),
    sa.Column('provider_type', sa.String(length=32), nullable=False),
    sa.Column('issuer', sa.String(length=512), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=False),
    sa.Column('email_hint', sa.String(length=320), nullable=True),
    sa.Column('assurance_capabilities', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('linked_by', sa.String(length=128), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant', 'issuer', 'subject', name='uq_identity_tenant_issuer_subject')
    )
    op.create_index(op.f('ix_identity_bindings_principal_id'), 'identity_bindings', ['principal_id'], unique=False)
    op.create_index(op.f('ix_identity_bindings_tenant'), 'identity_bindings', ['tenant'], unique=False)
    op.create_table('role_mailbox_assignments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant', sa.String(length=128), nullable=False),
    sa.Column('mailbox_id', sa.String(length=64), nullable=False),
    sa.Column('principal_id', sa.String(length=64), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_by', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['mailbox_id'], ['role_mailboxes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_mailbox_assignments_mailbox_id'), 'role_mailbox_assignments', ['mailbox_id'], unique=False)
    op.create_index(op.f('ix_role_mailbox_assignments_principal_id'), 'role_mailbox_assignments', ['principal_id'], unique=False)
    op.create_index(op.f('ix_role_mailbox_assignments_tenant'), 'role_mailbox_assignments', ['tenant'], unique=False)
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_mailbox_assignments_tenant'), table_name='role_mailbox_assignments')
    op.drop_index(op.f('ix_role_mailbox_assignments_principal_id'), table_name='role_mailbox_assignments')
    op.drop_index(op.f('ix_role_mailbox_assignments_mailbox_id'), table_name='role_mailbox_assignments')
    op.drop_table('role_mailbox_assignments')
    op.drop_index(op.f('ix_identity_bindings_tenant'), table_name='identity_bindings')
    op.drop_index(op.f('ix_identity_bindings_principal_id'), table_name='identity_bindings')
    op.drop_table('identity_bindings')
    op.drop_index(op.f('ix_detection_feedback_tenant'), table_name='detection_feedback')
    op.drop_index(op.f('ix_detection_feedback_risk_signal_id'), table_name='detection_feedback')
    op.drop_index(op.f('ix_detection_feedback_classification'), table_name='detection_feedback')
    op.drop_index(op.f('ix_detection_feedback_analyst_principal'), table_name='detection_feedback')
    op.drop_table('detection_feedback')
    op.drop_index(op.f('ix_contact_endpoints_tenant'), table_name='contact_endpoints')
    op.drop_index(op.f('ix_contact_endpoints_principal_id'), table_name='contact_endpoints')
    op.drop_table('contact_endpoints')
    op.drop_index(op.f('ix_approval_receipts_tenant'), table_name='approval_receipts')
    op.drop_index(op.f('ix_approval_receipts_request_id'), table_name='approval_receipts')
    op.drop_index(op.f('ix_approval_receipts_approver_principal'), table_name='approval_receipts')
    op.drop_table('approval_receipts')
    op.drop_index(op.f('ix_account_bindings_tenant'), table_name='account_bindings')
    op.drop_index(op.f('ix_account_bindings_principal_id'), table_name='account_bindings')
    op.drop_table('account_bindings')
    op.drop_index(op.f('ix_security_events_tenant'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_subject_ref'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_occurred_at'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_event_type'), table_name='security_events')
    op.drop_index('ix_event_subject_time', table_name='security_events')
    op.drop_table('security_events')
    op.drop_index(op.f('ix_role_mailboxes_tenant'), table_name='role_mailboxes')
    op.drop_table('role_mailboxes')
    op.drop_index(op.f('ix_risk_signals_tenant'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_subject_ref'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_severity'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_expires_at'), table_name='risk_signals')
    op.drop_table('risk_signals')
    op.drop_index(op.f('ix_response_actions_tenant'), table_name='response_actions')
    op.drop_index(op.f('ix_response_actions_state'), table_name='response_actions')
    op.drop_index(op.f('ix_response_actions_requester_principal'), table_name='response_actions')
    op.drop_index(op.f('ix_response_actions_operation'), table_name='response_actions')
    op.drop_index(op.f('ix_response_actions_expires_at'), table_name='response_actions')
    op.drop_table('response_actions')
    op.drop_index(op.f('ix_resource_classes_tenant'), table_name='resource_classes')
    op.drop_table('resource_classes')
    op.drop_index(op.f('ix_principals_tenant'), table_name='principals')
    op.drop_index(op.f('ix_principals_status'), table_name='principals')
    op.drop_table('principals')
    op.drop_index(op.f('ix_outbox_events_topic'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_tenant'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_state'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_next_attempt_at'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_aggregate_ref'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_grants_tenant'), table_name='grants')
    op.drop_index(op.f('ix_grants_subject_ref'), table_name='grants')
    op.drop_index(op.f('ix_grants_status'), table_name='grants')
    op.drop_table('grants')
    op.drop_index(op.f('ix_detector_definitions_tenant'), table_name='detector_definitions')
    op.drop_table('detector_definitions')
    op.drop_index(op.f('ix_delegations_to_principal'), table_name='delegations')
    op.drop_index(op.f('ix_delegations_tenant'), table_name='delegations')
    op.drop_index(op.f('ix_delegations_status'), table_name='delegations')
    op.drop_index(op.f('ix_delegations_from_principal'), table_name='delegations')
    op.drop_table('delegations')
    op.drop_index(op.f('ix_audit_records_tenant'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_exported'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_correlation_id'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_action'), table_name='audit_records')
    op.drop_table('audit_records')
    op.drop_index(op.f('ix_approval_requests_tenant'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_state'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_requester_principal'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_request_digest'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_expires_at'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_approval_policies_tenant'), table_name='approval_policies')
    op.drop_table('approval_policies')
    # ### end Alembic commands ###
